"""Copy a stopped local data snapshot into an EMPTY private cloud schema.
Run with DATABASE_URL, SUPABASE_URL and SUPABASE_SECRET_KEY in environment.
Never prints credentials. Local files are not changed.
"""
import argparse, os, re, sqlite3, sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from cloud_database import TABLES,ID_TABLES
import cloud_files

def schema(source):
    statements=['CREATE SCHEMA inventory','REVOKE ALL ON SCHEMA inventory FROM PUBLIC, anon, authenticated']
    for table in TABLES:
        ddl=source.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?",(table,)).fetchone()[0]
        ddl=ddl.replace('CREATE TABLE '+table,'CREATE TABLE inventory.'+table)
        ddl=re.sub(r'\bid INTEGER PRIMARY KEY\b','id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',ddl)
        ddl=re.sub(r'REFERENCES (\w+)\(',r'REFERENCES inventory.\1(',ddl)
        statements.extend([ddl,f'ALTER TABLE inventory.{table} ENABLE ROW LEVEL SECURITY',f'REVOKE ALL ON inventory.{table} FROM PUBLIC, anon, authenticated'])
    statements.append("CREATE FUNCTION inventory.reject_history_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Historical entries are immutable'; END $$")
    for table in ('movements','snapshots','audit'):
        statements.append(f'CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON inventory.{table} FOR EACH ROW EXECUTE FUNCTION inventory.reject_history_change()')
    statements.extend(['CREATE INDEX movements_item_date ON inventory.movements(item_id,date)','CREATE INDEX notification_inbox ON inventory.notifications(recipient_id,read_at,id)'])
    return statements

def main():
    p=argparse.ArgumentParser();p.add_argument('--data',required=True);p.add_argument('--apply',action='store_true');args=p.parse_args()
    root=Path(args.data).resolve()
    source=sqlite3.connect('file:'+str(root/'inventory.db')+'?mode=ro',uri=True)
    if source.execute('PRAGMA integrity_check').fetchone()[0]!='ok': raise SystemExit('Source integrity check failed')
    ddl=schema(source)
    counts={t:source.execute('SELECT count(*) FROM '+t).fetchone()[0] for t in TABLES}
    print('Source row counts:',counts)
    print('Private files:',sum(1 for folder in ('photos','reports') for f in (root/folder).glob('*') if f.is_file()))
    if not args.apply:
        print('Dry run complete. Stop local writes and use a snapshot before --apply.');return
    import psycopg
    from psycopg import sql
    with psycopg.connect(os.environ['DATABASE_URL'],sslmode='require',connect_timeout=15) as target:
        if target.execute("SELECT 1 FROM information_schema.schemata WHERE schema_name='inventory'").fetchone(): raise SystemExit('Target inventory schema already exists; refusing overwrite')
        for statement in ddl:target.execute(statement)
        for table in TABLES:
            cursor=source.execute('SELECT * FROM '+table);columns=[d[0] for d in cursor.description]
            query=sql.SQL('INSERT INTO inventory.{} ({}) VALUES ({})').format(sql.Identifier(table),sql.SQL(',').join(map(sql.Identifier,columns)),sql.SQL(',').join(sql.Placeholder() for _ in columns))
            with target.cursor() as writer:writer.executemany(query,cursor.fetchall())
            if table in ID_TABLES:
                target.execute("SELECT setval(pg_get_serial_sequence(%s,'id'), COALESCE((SELECT max(id) FROM inventory."+table+"),1), EXISTS(SELECT 1 FROM inventory."+table+'))',('inventory.'+table,))
            if target.execute('SELECT count(*) FROM inventory.'+table).fetchone()[0]!=counts[table]:raise RuntimeError('Row count mismatch')
        # Upload before committing DB: failures roll back the database migration.
        # An interrupted upload can leave private orphan files; rerun safely upserts them.
        _,_,bucket=cloud_files.config()
        buckets=cloud_files.call('GET','bucket').json()
        existing=next((b for b in buckets if b['id']==bucket),None)
        if existing and existing.get('public'):raise RuntimeError('Refusing public storage bucket')
        if not existing:cloud_files.call('POST','bucket',json={'id':bucket,'name':bucket,'public':False})
        for folder in ('photos','reports'):
            for file in (root/folder).glob('*'):
                if file.is_file():cloud_files.upload(root,folder+'/'+file.name)
        target.execute("INSERT INTO inventory.settings(key,value) VALUES('retention_years','4'),('retention_delete_enabled','false') ON CONFLICT(key) DO NOTHING")
    print('Migration committed. Verify logins, photos, reports and approvals before cutover.')

if __name__=='__main__':main()
